package com.dev.lvyou;

public class InterfaceList
{
  public static final String[] intfcName = { 
    "qryHotTouristSpotList", 
    "qryHotCityList", 
    "qryTouristSpotListByName", 
    "qryCityListByName", 
    "qryTouristSpotDetail", 
    "perfectInformation", 
    "qrySpotUserList", 
    "qryCityDetail", 
    "qryUserWantToSpotList", 
    "qryUserWantToCityList", 
    "qrySpotUserList", 
    "qryCityDetail", 
    "updateWantToSpots", 
    "updateWantToCity", 
    "publishMsg", 
    "qryDynamicInfo", 
    "userRegister", 
    "checkUserAuth", 
    "qryUserLoginInfo", 
    "qryProvinceList", 
    "qryCityList", 
    "albumManage", 
    "qryAlbumList", 
    "userImageManage", 
    "photoWallManage", 
    "qryUserImageList", 
    "queryUserInfoByUserName", 
    "queryDynamicinfo", 
    "dynamicinfoManage", 
    "publicDynamicComment", 
    "updateLocation", 
    "qryTouristSpotListBySid", 
    "updateWantToCity", 
    "qryCityUserList", 
    "qryCityBySid", 
    "qryWantToHeadUrlList", 
    "qryDynamicInfoById", 
    "qryNearSpots", 
    "togetherTourManage", 
    "qryTogetherTour", 
    "qqLogin", 
    "friendManager", 
    "friendsList", 
    "friendMeList", 
    "dynamicFabulous", 
    "dynamicReport", 
    "dynamicFabulousCount", 
    "friendsListCount", 
    "friendMeListCount" };
}